from __future__ import annotations

import argparse
import csv
import difflib
import hashlib
import json
import re
import shutil
from pathlib import Path


ROOT = Path(__file__).resolve().parent
AUTHORITY_SHA256 = "FA8BB92E58A4F78A2BD01B3B6A4A87DE0A0D279F5DD90641B574DD5FBFFFA4F3"
AUTHORITY_BYTES = 1_771_230
PRODUCER_SHA256 = "5D44E8D3B0CEA14832254B60F3A1795EB5D66D8EB184415D0C68911609747A2D"
PRODUCER_BYTES = 326_743
UPSTREAM_LOCK_SHA256 = "B195ECC83AB0F32C574A60D1FDBA9B0DA4D35B04E0DF7CB106DC9C0FDAD99C0D"
COPYING_SHA256 = "4B2C8FC390F802CD92F0622DC00A708A588BEC54D0145D2EE135D6D7672BFE85"
GENERATED_AT = "2026-08-24T02:50:18Z"

CONTROL_EVIDENCE = {
    "DECISION_20260824_R6_ALG_266_313.json": "63CDDEE4237836883116B36D47C636DBBF47A6F6415949FA418BFC6F65A72A18",
    "DECISION_20260824_R6_ALG_314.json": "F3934656B6524F4D2000DC3DD11A1B0049672DC95C63391E88B08C9E55B0CA80",
    "R6_ALG_266_313_INTAKE.json": "BF1B2038B12ED07487005593774EBC86225E595D47E599640984D87CF88C57BA",
    "R6_ALG_266_313_REPLAY.json": "37C1C0E910CF30F4DCD82D32724D8E06E9D180BDEF29608314BBD7387634E01A",
    "R6_ALG_266_313_REVIEW.md": "01A2E072C796950BFA3E7612A350A30CE2FB34823AA5EF4DC4E095C6DB341A4C",
    "R6_ALG_314_INTAKE.json": "B3CE97574077D577DF9BE5EEB6494AB18D0C09F3B29EA9BA94A01FCE6DCB7DED",
    "R6_ALG_314_REPLAY.json": "10256B834B5F943315774E249B0206C192FE8D0839EF5CB67687C6AED7A48148",
    "R6_ALG_314_REVIEW.md": "43FE9C5CF6F1D205972EA3513715B8BB32C1483BA52FEB29CA4FCAF663D43E9D",
}


def op(producer: int, line_start: int, line_end: int, old: str, new: str) -> dict:
    return {
        "producer_id": f"ALGEBRA-{producer}",
        "source_start_line": line_start,
        "source_end_line": line_end,
        "old_text": old,
        "replacement_text": new,
    }


OPERATIONS = [
    op(266, 28905, 28905, "exist by Lemma \\ref{lemma-dominate}).", "exists by Lemma \\ref{lemma-dominate})."),
    op(267, 28934, 28937,
       "\\item there exists a finite ring map $R \\to R'$ which is not\n"
       "an isomorphism whose kernel and cokernel are annihilated by a power\n"
       "of $\\mathfrak m$ such that $\\mathfrak m$ is not an associated\n"
       "prime of $R'$ and $R' \\not = 0$.",
       "\\item there exists a finite ring map $R \\to R'$ which is not\n"
       "an isomorphism, has kernel and cokernel annihilated by a power of\n"
       "$\\mathfrak m$, satisfies $\\mathfrak m \\notin \\operatorname{Ass}(R')$,\n"
       "and has $R' \\not = 0$."),
    op(268, 28992, 28992, "in the generic point", "at the generic point"),
    op(270, 29098, 29100,
       "On the other hand, if the completion of $R$ in all of its maximal\n"
       "ideals is reduced, then the procedure stops (insert future reference\n"
       "here).",
       "On the other hand, if the completion of $R$ at each of its maximal\n"
       "ideals is reduced, then the procedure stops."),
    op(271, 29114, 29116,
       "$u\\pi^n$, where $u \\in A$ is a unit.",
       "$u\\pi^n$, where $u \\in A$ is a unit and $n \\in \\mathbf{Z}_{\\geq 0}$."),
    op(273, 29194, 29194, "as a vectors space", "as a vector space"),
    op(274, 29224, 29224,
       "0 \\subset N_0 \\subset N_1 \\subset N_2 \\subset \\ldots N_k \\subset M/xM",
       "0 \\subset N_0 \\subset N_1 \\subset N_2 \\subset \\ldots \\subset N_k \\subset M/xM"),
    op(275, 29261, 29261,
       "structural results on Artinian rings implies parts (1) and (2)",
       "structural results on Artinian rings imply parts (1) and (2)"),
    op(276, 29316, 29316,
       "Then there exists discrete valuation ring $A$ with fraction field",
       "Then there exists a discrete valuation ring $A$ with fraction field"),
    op(277, 29363, 29364,
       "\\item An element $x \\in R$ is called {\\it prime} if the ideal\n"
       "generated by $x$ is a prime ideal.",
       "\\item A nonzero element $x \\in R$ is called {\\it prime} if the ideal\n"
       "generated by $x$ is a prime ideal."),
    op(278, 29377, 29377, "for some $f, g \\in A$.", "for some $f, g \\in R$."),
    op(279, 29378, 29378,
       "Then $x = fg x$ and since $R$ is a domain $fg = 1$. Thus",
       "If $x = 0$, then also $y = 0$, and the conclusion is immediate.\n"
       "Otherwise, $x = fg x$ and since $R$ is a domain $fg = 1$. Thus"),
    op(281, 29435, 29436,
       "Say $ab \\in (x)$, i.e., $ab = cx$. Choose factorizations",
       "Say $ab \\in (x)$, i.e., $ab = cx$. If $a = 0$ or $b = 0$, the\n"
       "conclusion is immediate. Thus $a$, $b$, and $c$ are nonzero. Choose\n"
       "factorizations (allowing the empty product for a unit)"),
    op(282, 29453, 29455,
       "and $a_2 \\ldots a_n = ub_2\\ldots b_m$. By induction on $n + m$\n"
       "we see that $n = m$ and $a_i$ associate to $b_{\\sigma(i)}$ for\n"
       "$i = 2, \\ldots, n$ as desired.",
       "and $a_2 \\ldots a_m = ub_2\\ldots b_n$. If $m = 1$ or $n = 1$,\n"
       "this equality forces $m = n = 1$. Otherwise, absorb $u$ into $b_2$\n"
       "and apply induction on $n + m$ to see that $n = m$ and $a_i$ is\n"
       "associate to $b_{\\sigma(i)}$ for $i = 2, \\ldots, n$, as desired."),
    op(283, 29550, 29550,
       "of principal ideals in $R$. Write $a_1 = p_1^{e_1} \\ldots p_r^{e_r}$",
       "of principal ideals in $R$. If $a_n = 0$ for every $n$, there is\n"
       "nothing to prove. Otherwise, after dropping an initial segment and\n"
       "renumbering, we may assume $a_1 \\not = 0$. Write\n"
       "$a_1 = p_1^{e_1} \\ldots p_r^{e_r}$"),
    op(284, 29565, 29565,
       "of principal ideals in $R[x]$. Since",
       "of principal ideals in $R[x]$. If $f_n = 0$ for every $n$, there is\n"
       "nothing to prove. Otherwise, after dropping an initial segment and\n"
       "renumbering, we may assume $f_1 \\not = 0$. Since"),
    op(285, 29589, 29589, "element of $R[x]$", "nonzero nonunit element of $R[x]$"),
    op(285, 29592, 29592, "every nonunit of $R$", "every nonzero nonunit of $R$"),
    op(286, 29608, 29608,
       "We can write",
       "If $x = 0$, there is nothing to prove. Thus we may assume $x \\not = 0$ and write"),
    op(288, 29699, 29699,
       "$\\mathfrak p \\subset R$ be a prime ideal. Observe that",
       "$\\mathfrak p \\subset R$ be a nonzero prime ideal (the zero ideal is already finitely generated). Observe that"),
    op(290, 29728, 29728,
       "prime ideal $\\mathfrak p$", "nonzero maximal ideal $\\mathfrak m$"),
    op(291, 29735, 29735,
       "Let $I \\subset R$ be an ideal.",
       "The unit ideal is the empty product. Let $I \\subset R$ be a nonzero proper ideal."),
    op(297, 29442, 29442,
       "$a_1, \\ldots, b_m$", "$a_1, \\ldots, a_n, b_1, \\ldots, b_m$"),
    op(298, 29869, 29869, "M/M \\cap M'", "M/(M \\cap M')"),
    op(298, 29869, 29869, "M'/M \\cap M'", "M'/(M \\cap M')"),
    op(298, 29873, 29873, "M + M' / M'", "(M + M')/M'"),
    op(298, 29873, 29873, "M + M'/M", "(M + M')/M"),
    op(298, 29940, 29940, "M/M \\cap M'", "M/(M \\cap M')"),
    op(298, 29940, 29940, "M'/M \\cap M'", "M'/(M \\cap M')"),
    op(299, 29997, 29997,
       "d(M, \\varphi(\\psi((M))) & = &",
       "d(M, \\varphi(\\psi((M)))) & = &"),
    op(300, 30032, 30032, "R^{\\oplus b}", "R^{\\oplus n}"),
    op(301, 30334, 30336, "it is Artinian ring", "it is an Artinian ring"),
    op(302, 30381, 30386,
       "the stability of finite type property under base change",
       "the stability of the finite type property under base change"),
    op(303, 30432, 30441, "$P(x_i)^{e_i} = 0$", "$P_i(x_i)^{e_i} = 0$"),
    op(303, 30442, 30445, "$P(x_i)^{e_i} = 0$", "$P_i(x_i)^{e_i} = 0$"),
    op(304, 30487, 30490,
       "Namely, multiply the equation",
       "If $n = 0$, then $\\varphi(a_0)t = 0$ and the assertion is immediate.\n"
       "Otherwise, multiply the equation"),
    op(305, 30488, 30491,
       "with $\\varphi(a_n)^{n-1}$", "by $\\varphi(a_n)^{n-1}$"),
    op(306, 30570, 30580,
       "Assume $\\varphi(R) \\subset S$ integrally closed in $S$.",
       "Assume that $\\varphi(R)$ is integrally closed in $S$."),
    op(307, 30713, 30718,
       "Assume $x \\in S$ be strongly transcendental over $R$",
       "Assume $x \\in S$ is strongly transcendental over $R$"),
    op(308, 30754, 30756,
       "The base case is\n$m = 0$ is vacuous", "The base case\n$m = 0$ is vacuous"),
    op(309, 30759, 30763,
       "$b_mx \\in S'$ by\nLemma \\ref{lemma-make-integral-trivial}.",
       "$b_mx \\in S'$: Lemma \\ref{lemma-make-integral-trivial} makes it\n"
       "integral over $S'$, hence over $R$ by Lemma\n"
       "\\ref{lemma-integral-transitive}, so the definition of $S'$ applies."),
    op(309, 30765, 30768,
       "$b_mx \\in S'$ by\nLemma \\ref{lemma-make-integral-trivial}.",
       "$b_mx \\in S'$: Lemma \\ref{lemma-make-integral-trivial} makes it\n"
       "integral over $S'$, hence over $R$ by Lemma\n"
       "\\ref{lemma-integral-transitive}, so the definition of $S'$ applies."),
    op(310, 30778, 30785,
       "Let $R \\to S$ be a finite type $R$-algebra.",
       "Let $S$ be a finite type $R$-algebra."),
    op(312, 30789, 30793,
       "(For\nexample generators of $S$ over $R$.)",
       "(For\nexample, generators of $S$ over $R$.)"),
    op(311, 30789, 30793, "We prove the proposition", "We prove the theorem"),
    op(313, 30859, 30861,
       "Surjectivity\nbecause of how we chose $y_i$, injectivity because\n"
       "$R'' \\subset R'$, and localization is exact.",
       "Surjectivity follows from the choice of the $y_i$; injectivity follows\n"
       "from $R'' \\subset R'$ and the exactness of localization."),
    op(314, 30969, 30971,
       "\\end{enumerate}\nThen $B$ is semi-local.",
       "\\end{enumerate}\nAssume moreover that $B$ is not a field.\nThen $B$ is semi-local."),
]


REJECTED = {
    272: "Established contextual shorthand; quotient-polynomial parenthesization repeats rejected ALGEBRA-208.",
    280: "The stronger two-factor choice follows by factoring a nonfactorable factor again.",
    287: "Valid standard shorthand from UFD element factorization to principal prime ideals.",
    289: "The local-ring unit inference is correct and routine.",
    292: "Strictness for Noetherian induction follows after localization.",
    293: "The source explicitly marks an omitted proof and makes no false assertion.",
    294: "Successive cancellation handles repeated prime factors.",
    295: "The standard empty-product convention covers the unit ideal.",
    296: "Normality follows from the integral closure in the field L.",
}
UNRESOLVED = {
    269: "The local-to-global gap is real, but no unique proof-backed global correction or exact citation has been established."
}


def sha_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest().upper()


def sha256(path: Path) -> str:
    return sha_bytes(path.read_bytes())


def write_json(path: Path, data: object) -> None:
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2, sort_keys=True) + "\n", encoding="utf-8", newline="")


def evidence(path: Path, relative: str) -> dict:
    return {"path": relative, "bytes": path.stat().st_size, "sha256": sha256(path)}


def line_offsets(data: bytes) -> list[int]:
    starts = [0]
    for match in re.finditer(b"\n", data):
        starts.append(match.end())
    return starts


def exact_operations(authority: bytes) -> list[dict]:
    starts = line_offsets(authority)
    mapped = []
    per_producer: dict[str, int] = {}
    for row in OPERATIONS:
        producer = row["producer_id"]
        per_producer[producer] = per_producer.get(producer, 0) + 1
        scope_start = starts[row["source_start_line"] - 1]
        scope_end = starts[row["source_end_line"]] if row["source_end_line"] < len(starts) else len(authority)
        old = row["old_text"].encode("utf-8")
        new = row["replacement_text"].encode("utf-8")
        scope = authority[scope_start:scope_end]
        if scope.count(old) != 1:
            raise AssertionError(f"{producer}: old span is not unique in bounded lines")
        start = scope_start + scope.index(old)
        end = start + len(old)
        mapped.append({
            **row,
            "operation_index": per_producer[producer],
            "start_byte": start,
            "end_byte_exclusive": end,
            "occurrence_count_in_frozen_authority": authority.count(old),
            "old_bytes": len(old),
            "old_sha256": sha_bytes(old),
            "replacement_bytes": len(new),
            "replacement_sha256": sha_bytes(new),
        })
    ordered = sorted(mapped, key=lambda row: row["start_byte"])
    for left, right in zip(ordered, ordered[1:]):
        if left["end_byte_exclusive"] > right["start_byte"]:
            raise AssertionError(f"overlap: {left['producer_id']} / {right['producer_id']}")
    return mapped


def apply_operations(authority: bytes, mapped: list[dict]) -> bytes:
    payload = authority
    for row in sorted(mapped, key=lambda item: item["start_byte"], reverse=True):
        start, end = row["start_byte"], row["end_byte_exclusive"]
        old = row["old_text"].encode("utf-8")
        new = row["replacement_text"].encode("utf-8")
        if payload[start:end] != old:
            raise AssertionError(f"replay interval mismatch: {row['producer_id']}")
        payload = payload[:start] + new + payload[end:]
    return payload


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--authority", type=Path, required=True)
    parser.add_argument("--producer-ledger", type=Path, required=True)
    parser.add_argument("--control-root", type=Path, required=True)
    parser.add_argument("--upstream-lock", type=Path, required=True)
    parser.add_argument("--copying", type=Path, required=True)
    args = parser.parse_args()

    authority = args.authority.read_bytes()
    if len(authority) != AUTHORITY_BYTES or sha_bytes(authority) != AUTHORITY_SHA256:
        raise AssertionError("frozen authority identity mismatch")
    if b"\r" in authority or not authority.endswith(b"\n"):
        raise AssertionError("authority is not terminal-LF UTF-8/LF source")
    if args.producer_ledger.stat().st_size != PRODUCER_BYTES or sha256(args.producer_ledger) != PRODUCER_SHA256:
        raise AssertionError("producer ledger identity mismatch")
    if sha256(args.upstream_lock) != UPSTREAM_LOCK_SHA256 or sha256(args.copying) != COPYING_SHA256:
        raise AssertionError("upstream lock or COPYING identity mismatch")
    for name, expected in CONTROL_EVIDENCE.items():
        if sha256(args.control_root / name) != expected:
            raise AssertionError(f"control evidence mismatch: {name}")

    producer_ids = {row["id"] for row in csv.DictReader(args.producer_ledger.read_text(encoding="utf-8").splitlines())}
    required = {f"ALGEBRA-{number}" for number in range(266, 315)}
    if not required.issubset(producer_ids):
        raise AssertionError("producer ledger no longer contains complete ALGEBRA-266..314 intake")

    generated = [ROOT / "authority", ROOT / "payload", ROOT / "candidate.config.json",
                 ROOT / "stable-units.json", ROOT / "source-map.jsonl", ROOT / "decisions.jsonl",
                 ROOT / "rejections.jsonl", ROOT / "formula-diagram-inventory.json",
                 ROOT / "operation-spec.json"]
    if any(path.exists() for path in generated):
        raise FileExistsError("candidate material already exists; materializer refuses to overwrite")

    mapped = exact_operations(authority)
    if len(mapped) != 47:
        raise AssertionError("operation closure mismatch")
    payload = apply_operations(authority, mapped)

    authority_source = ROOT / "authority" / "source" / "algebra.tex"
    producer_copy = ROOT / "authority" / "producer" / "SOURCE_DEFECT_LEDGER.csv"
    canon_root = ROOT / "authority" / "canon"
    payload_path = ROOT / "payload" / "algebra.tex"
    authority_source.parent.mkdir(parents=True)
    producer_copy.parent.mkdir(parents=True)
    canon_root.mkdir(parents=True)
    payload_path.parent.mkdir(parents=True)
    authority_source.write_bytes(authority)
    payload_path.write_bytes(payload)
    shutil.copy2(args.producer_ledger, producer_copy)
    shutil.copy2(args.upstream_lock, ROOT / "authority" / "upstream.lock.json")
    shutil.copy2(args.copying, ROOT / "authority" / "COPYING")
    for name in CONTROL_EVIDENCE:
        shutil.copy2(args.control_root / name, canon_root / name)

    decision_rows = []
    replay_rows = []
    for name in ("DECISION_20260824_R6_ALG_266_313.json", "DECISION_20260824_R6_ALG_314.json"):
        decision_rows.extend(json.loads((args.control_root / name).read_text(encoding="utf-8"))["accepted"])
    for name in ("R6_ALG_266_313_REPLAY.json", "R6_ALG_314_REPLAY.json"):
        replay_rows.extend(json.loads((args.control_root / name).read_text(encoding="utf-8"))["accepted"])
    decision_by_producer = {row["producer_id"]: row for row in decision_rows}
    replay_by_producer = {row["producer_id"]: row for row in replay_rows}
    accepted_ids = [f"MC-STK-ERR-{number:04d}" for number in range(621, 660)]
    if [row["canon_id"] for row in decision_rows] != accepted_ids:
        raise AssertionError("stable-ID assignment differs from bounded decisions")

    ops_by_producer: dict[str, list[dict]] = {}
    for row in mapped:
        ops_by_producer.setdefault(row["producer_id"], []).append(row)
    stable_units = []
    source_rows = []
    formula_units, prose_units = [], []
    for decision in decision_rows:
        producer = decision["producer_id"]
        stable_id = decision["canon_id"]
        operations = sorted(ops_by_producer[producer], key=lambda row: row["operation_index"])
        operation_rows = []
        for row in operations:
            operation_rows.append({
                "operation_id": f"{stable_id}-OP{row['operation_index']}",
                "source_start_line": row["source_start_line"],
                "source_end_line": row["source_end_line"],
                "start_byte": row["start_byte"],
                "end_byte_exclusive": row["end_byte_exclusive"],
                "occurrence_count_in_frozen_authority": row["occurrence_count_in_frozen_authority"],
                "old_bytes": row["old_bytes"],
                "old_sha256": row["old_sha256"],
                "replacement_bytes": row["replacement_bytes"],
                "replacement_sha256": row["replacement_sha256"],
                "old_text": row["old_text"],
                "replacement_text": row["replacement_text"],
            })
        locus = "algebra.tex:" + decision["locus"]
        operation_ids = [row["operation_id"] for row in operation_rows]
        stable_units.append({
            "id": stable_id,
            "producer_id": producer,
            "class": decision["classification"],
            "source": "algebra.tex",
            "locus": locus,
            "payload": "payload/algebra.tex",
            "operation_ids": operation_ids,
            "status": "applied",
        })
        replay = replay_by_producer[producer]
        source_rows.append({
            "schema": "mathematics-commons-stacks-errata-map/v2",
            "unit_id": stable_id,
            "producer_id": producer,
            "source": "algebra.tex",
            "authority": "authority/source/algebra.tex",
            "authority_sha256": AUTHORITY_SHA256,
            "payload": "payload/algebra.tex",
            "locus": locus,
            "class": decision["classification"],
            "proof": f"Independent replay result: {replay['result']}. {replay['smallest_correction']}",
            "adverse_evidence": "Exact frozen-source and mathematical review evidence is bound under authority/canon; no translation or authority byte was used as the corrected payload.",
            "operations": operation_rows,
        })
        has_tex = any(("$" in row["old_text"] or "\\" in row["old_text"] or
                       "$" in row["replacement_text"] or "\\" in row["replacement_text"])
                      for row in operations)
        (formula_units if has_tex else prose_units).append(stable_id)

    write_json(ROOT / "stable-units.json", {
        "schema": "mathematics-commons-stacks-errata-units/v1",
        "authority_commit": "a04446e57ec1fbc252a871afcec7752fb2807b14",
        "unit_count": len(stable_units),
        "units": stable_units,
    })
    (ROOT / "source-map.jsonl").write_text(
        "".join(json.dumps(row, ensure_ascii=False, separators=(",", ":")) + "\n" for row in source_rows),
        encoding="utf-8", newline="",
    )
    write_json(ROOT / "formula-diagram-inventory.json", {
        "schema": "mathematics-commons-stacks-errata-formula-diagram-inventory/v1",
        "candidate_id": "stacks-errata-a04446e-r6",
        "unit_count": len(stable_units),
        "formula_units": formula_units,
        "diagram_units": [],
        "prose_only_units": prose_units,
        "classification": "Each mapped unit is classified exactly once from its corrected span; no xymatrix span is changed.",
        "unmapped_formula_or_diagram_changes": 0,
    })
    write_json(ROOT / "operation-spec.json", {
        "schema": "mathematics-commons-stacks-errata-operation-spec/v1",
        "authority_sha256": AUTHORITY_SHA256,
        "operation_count": len(mapped),
        "apply_order": "descending_start_byte",
        "operations": mapped,
    })

    decisions = [
        ("ERR-R6-D0001", "Bind R6 exclusively to the active errata/r6 lease and frozen upstream commit/tree.", "Preserves the single-writer and immutable-authority boundary."),
        ("ERR-R6-D0002", "Assign MC-STK-ERR-0621..0659 by ascending producer identity after admitted R5 and later proven R6 dispositions.", "Creates a deterministic, globally unique stable-ID sequence."),
        ("ERR-R6-D0003", "Apply only exact nonoverlapping half-open UTF-8 spans in descending byte order.", "Prevents contextual or global replacement from changing unrelated text."),
        ("ERR-R6-D0004", "Keep ALGEBRA-269 unresolved and unapplied.", "The proof gap is real, but no unique proof-backed global repair was established."),
        ("ERR-R6-D0005", "Retain all nine disproved producer allegations as rejection evidence.", "An errata edition must distinguish proved defects from merely plausible critiques."),
        ("ERR-R6-D0006", "Keep canonical locale bytes and the literal upstream mirror outside the corrected English payload.", "Corrections belong only to Stacks — English AI Edition."),
        ("ERR-R6-D0007", "Do not contact or submit this AI-derived correction set to upstream Stacks maintainers.", "The maintained AI-open English edition is the authorized correction surface."),
    ]
    (ROOT / "decisions.jsonl").write_text("".join(
        json.dumps({"schema": "mathematics-commons-stacks-candidate-decision/v1", "id": row[0],
                    "timestamp_utc": GENERATED_AT, "choice": row[1], "rationale": row[2], "supersedes": None},
                   separators=(",", ":")) + "\n" for row in decisions), encoding="utf-8", newline="")
    rejection_rows = []
    counter = 1
    for number, reason in sorted(REJECTED.items()):
        rejection_rows.append({"schema": "mathematics-commons-stacks-candidate-rejection/v1",
                               "id": f"ERR-R6-R{counter:04d}", "timestamp_utc": GENERATED_AT,
                               "producer_id": f"ALGEBRA-{number}", "disposition": "rejected", "reason": reason})
        counter += 1
    for number, reason in sorted(UNRESOLVED.items()):
        rejection_rows.append({"schema": "mathematics-commons-stacks-candidate-rejection/v1",
                               "id": f"ERR-R6-R{counter:04d}", "timestamp_utc": GENERATED_AT,
                               "producer_id": f"ALGEBRA-{number}", "disposition": "candidate_unproved", "reason": reason})
    (ROOT / "rejections.jsonl").write_text("".join(
        json.dumps(row, separators=(",", ":")) + "\n" for row in rejection_rows), encoding="utf-8", newline="")

    ref_pattern = re.compile(rb"\\(?:ref|eqref|pageref|autoref)\{[^{}]+\}")
    before_refs = ref_pattern.findall(authority)
    after_refs = ref_pattern.findall(payload)
    additions = []
    matcher = difflib.SequenceMatcher(a=before_refs, b=after_refs, autojunk=False)
    for tag, i1, i2, j1, j2 in matcher.get_opcodes():
        if tag == "equal":
            continue
        if tag != "insert":
            raise AssertionError(f"unexpected ordered-reference change: {tag} {i1}:{i2} {j1}:{j2}")
        for index in range(j1, j2):
            additions.append({"index_0based": index, "payload": after_refs[index].decode("utf-8"),
                              "producer_id": "ALGEBRA-309", "stable_id": "MC-STK-ERR-0654"})

    authority_evidence = []
    for path in sorted((ROOT / "authority").rglob("*")):
        if path.is_file():
            authority_evidence.append(evidence(path, path.relative_to(ROOT).as_posix()))
    config = {
        "schema": "mathematics-commons-stacks-errata-candidate-config/v1",
        "candidate_id": "stacks-errata-a04446e-r6",
        "lease_id": "stacks-lease-000009-errata-r6",
        "writer_task": "01a0256d-5693-77c1-96b2-cf37101e0c6c",
        "authority_commit": "a04446e57ec1fbc252a871afcec7752fb2807b14",
        "authority_tree": "3feeb703b931a6e7259782c10e7d1575adc83e5e",
        "source_date_epoch": "1785270512",
        "expected_unit_ids": accepted_ids,
        "operation_count": len(mapped),
        "stems": {
            "algebra": {
                "authority_sha256": AUTHORITY_SHA256,
                "payload_sha256": sha_bytes(payload),
                "authority_bytes": len(authority),
                "payload_bytes": len(payload),
                "display_delimiter_delta": 0,
                "ordered_structure_exceptions": {"references_added": additions},
                "build_exceptions": {
                    "candidate_only_undefined_reference_targets": {},
                    "candidate_page_delta": 0,
                },
            }
        },
        "authority_evidence": authority_evidence,
        "proof_closure": {
            "producer_rows": 49,
            "accepted": 39,
            "operations": 47,
            "rejected": 9,
            "prior_overlay_aliases": 0,
            "packet_duplicates": 0,
            "unresolved": 1,
        },
    }
    write_json(ROOT / "candidate.config.json", config)
    print(json.dumps({"passed": True, "units": 39, "operations": 47,
                      "payload_bytes": len(payload), "payload_sha256": sha_bytes(payload),
                      "reference_additions": additions}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
